CC=gcc
FLAGS=-Wall -O -pthread


all: THREAD1 THREAD_TIMING THREAD3 THREAD4 THREAD7 THREAD8

THREAD1: thread1.c
	$(CC) $(FLAGS) -o THREAD1 $^

THREAD_TIMING: thread_timing.c
	$(CC) $(FLAGS) -o THREAD_TIMING $^

THREAD3: thread3.c
	$(CC) $(FLAGS) -o THREAD3 $^

THREAD4: thread4.c
	$(CC) $(FLAGS) -o THREAD4 $^

THREAD7: thread7.c
	$(CC) $(FLAGS) -o THREAD7 $^

THREAD8: thread8.c
	$(CC) $(FLAGS) -o THREAD8 $^

