CC = gcc
CFLAGS = -lcrypto -O2

.PHONY: all

all: problem3 problem4 problem5 problem6 problem7

problem3: problem3.c 
	$(CC) -o $@ $^ $(CFLAGS)
problem4: problem4.c 
	$(CC) -o $@ $^ $(CFLAGS)
problem5: problem5.c 
	$(CC) -o $@ $^ $(CFLAGS)
problem6: problem6.c 
	$(CC) -o $@ $^ $(CFLAGS)
problem7: problem7.c 
	$(CC) -o $@ $^ $(CFLAGS)



